name: Build Desktop Application

on:
  push:
    branches: [develop, master]

defaults:
  run:
    shell: powershell

jobs:
  build:
    name: Build Windows App
    runs-on: windows-2025
    env:
      SIGNTOOL_PATH: 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x86/signtool.exe'
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Run Pack Script
        run: pnpm run node scripts/pack.ts
        working-directory: apps/desktop

      - name: Build MSI Package
        run: pnpm run build --publish never -w msi
        working-directory: apps/desktop